-- ============================================================
-- Estrutura do banco - SoftGroup
-- Este arquivo e executado nativamente pelo Spring Boot antes
-- do data.sql. O Hibernate/JPA nao cria mais as tabelas.
-- ============================================================

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    cargo VARCHAR(50) NOT NULL,
    tipo_perfil VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'ATIVO',
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_tipo_perfil CHECK (tipo_perfil IN ('ADMIN', 'LIDER', 'COLABORADOR')),
    CONSTRAINT ck_usuario_status CHECK (status IN ('ATIVO', 'INATIVO'))
);

CREATE TABLE IF NOT EXISTS equipe (
    id_equipe INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    CONSTRAINT uk_equipe_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS usuario_equipe (
    id_usuario INTEGER NOT NULL,
    id_equipe INTEGER NOT NULL,
    CONSTRAINT pk_usuario_equipe PRIMARY KEY (id_usuario, id_equipe),
    CONSTRAINT fk_usuario_equipe_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT fk_usuario_equipe_equipe FOREIGN KEY (id_equipe)
        REFERENCES equipe (id_equipe)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS softskill (
    id_softskill INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    CONSTRAINT uk_softskill_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS nivel_avaliacao (
    id_nivelavaliacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    cor VARCHAR(20) NOT NULL,
    faixa_min INTEGER NOT NULL,
    faixa_max INTEGER NOT NULL,
    CONSTRAINT uk_nivel_avaliacao_cor UNIQUE (cor),
    CONSTRAINT ck_nivel_avaliacao_cor CHECK (cor IN ('AZUL', 'VERDE', 'AMARELO', 'VERMELHO')),
    CONSTRAINT ck_nivel_avaliacao_faixa CHECK (
        faixa_min >= 0
        AND faixa_max <= 100
        AND faixa_min <= faixa_max
    )
);

CREATE TABLE IF NOT EXISTS ciclo (
    id_ciclo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT uk_ciclo_nome UNIQUE (nome),
    CONSTRAINT ck_ciclo_status CHECK (status IN ('ABERTO', 'FECHADO')),
    CONSTRAINT ck_ciclo_periodo CHECK (data_fim >= data_inicio)
);

CREATE TABLE IF NOT EXISTS avaliacao (
    id_avaliacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_avaliador INTEGER NOT NULL,
    id_avaliado INTEGER NOT NULL,
    id_softskill INTEGER NOT NULL,
    id_ciclo INTEGER NOT NULL,
    nota INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anonimato BOOLEAN DEFAULT FALSE,
    data TIMESTAMP,
    CONSTRAINT fk_avaliacao_avaliador FOREIGN KEY (id_avaliador)
        REFERENCES usuario (id_usuario),
    CONSTRAINT fk_avaliacao_avaliado FOREIGN KEY (id_avaliado)
        REFERENCES usuario (id_usuario),
    CONSTRAINT fk_avaliacao_softskill FOREIGN KEY (id_softskill)
        REFERENCES softskill (id_softskill),
    CONSTRAINT fk_avaliacao_ciclo FOREIGN KEY (id_ciclo)
        REFERENCES ciclo (id_ciclo),
    CONSTRAINT uk_avaliacao_resposta UNIQUE (
        id_avaliador,
        id_avaliado,
        id_softskill,
        id_ciclo,
        tipo
    ),
    CONSTRAINT ck_avaliacao_nota CHECK (nota BETWEEN 0 AND 100),
    CONSTRAINT ck_avaliacao_tipo CHECK (tipo IN ('AUTO', 'LIDER', '360'))
);

CREATE INDEX IF NOT EXISTS idx_usuario_equipe_equipe
    ON usuario_equipe (id_equipe);

CREATE INDEX IF NOT EXISTS idx_avaliacao_avaliado_ciclo
    ON avaliacao (id_avaliado, id_ciclo);

CREATE INDEX IF NOT EXISTS idx_avaliacao_avaliador_ciclo
    ON avaliacao (id_avaliador, id_ciclo);

CREATE INDEX IF NOT EXISTS idx_avaliacao_ciclo
    ON avaliacao (id_ciclo);
